### ISSUE TITLE
Base07 and Base05 should be swapped.

### ISSUE THREAD

**Issue by Corey-Keller** [jonleopard/base16-papercolor-scheme#1]
Or at least "#444444" should be Base05, assuming that is the value you intended for the main foreground (because according to the [Styling Guidelines](https://github.com/chriskempson/base16/blob/master/styling.md) Base05 is supposed to be the normal foreground.)

**Comment by jonleopard** [comment]
Hey @Corey-Keller,

Just now seeing this! Thanks for your input, I went and applied your suggestions here 369290e so you can go ahead and pull in the latest changes. Have you tried the dark version yet? To me, the theme doesn't look exactly correct on either dark or light versions. I've tried getting additional input from the theme author [here](https://github.com/NLKNguyen/papercolor-theme/issues/113) but haven't gotten any response yet.

Let me know what you think, and if you have any additional suggestions!

Cheers
